### ISSUE TITLE
Project license? -> LGPL 2.1

### ISSUE THREAD

**Issue by BurningEnlightenment** [MinecraftForge/Installer#29]
Hi,

Under which license can I utilize this project (specifically its sources)?

Cheers,
Henrik

**Comment by LexManos** [comment]
Interesting could of sworn we had it in there at some time.
LGPL 2.1 just like FML, and Forge will be once we get around doing it all.
The general concept is 'Do whatever you want, just dont claim as your own'

**Comment by BurningEnlightenment** [comment]
Awesome! :+1:
