### ISSUE TITLE
[FEATURE] More support for commandline 

### ISSUE THREAD

**Issue by MakerTim** [MinecraftForge/Installer#32]
Would it be possible that i can add arguments to the installer so i can force the client install?
i wanna use the installer because for better support of my launcher, but now the people press ok to install
and for server they even need to select stuff,
would it be a possible to add arguments so you can --installClient or something that people doesn't have to see the installer anymore?
and the same kind of deal for servers
"--installServer -d /user/var/....."

**Comment by deltaidea** [comment]
Why was this closed?

**Comment by LexManos** [comment]
See the 10 other requests for this.
