### ISSUE TITLE
Installer breaks file formatting

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/Installer#37]
I noticed this because I used an 'ü' in the file path. This works very good but as soon as you run the forge installer it updfates the forge profile and thus rewriting the profiles-file. After this change the ü is changed to something like this '�'. Thew vanilla launcher uses ANSI as encoding.

EDIT:
after loking into the code the file is openend and gets saved as UTF-8 and not as ANSI (ISO_8859_1) as the launcher does. (https://github.com/MinecraftForge/Installer/blob/master/src/main/java/net/minecraftforge/installer/ClientInstall.java#L284-L319)

**Comment by LexManos** [comment]
One of these days Mojang will specify the actual format for the launcher jsons.
UTF8 is the current default for compatibility reasons.
There isn't much we can do to auto detect what encoding the files are in, so while it's undocumented we'll go with UTF8.
