### ISSUE TITLE
Quick question about OptionParser?

### ISSUE THREAD

**Issue by TheMerkyShadow** [MinecraftForge/Installer#46]
Is there a specific reason to not allow devs to to set OptionParser settings and the [target] for the ".minecraft" directory via startup arguments? Cause that seems mysteriously left out?

**Comment by LexManos** [comment]
Because I do not want a no-effort auto installer for clients. If you're going to bypass how I make income on Forge, then put a small amount of effort into doing it yourself.

**Comment by TheMerkyShadow** [comment]
@LexManos that doesn't really make a whole lot of sense. If someone builds a no effort installation for people they are going to provide the forge regardless...So your argument invalid. Your just making it more annoying for developers.

Edit: forked it and put a small amount of effort needed to do it myself.

**Comment by LexManos** [comment]
Yes that small amount of annoyance is the point.
Twitch Client exists if you want to install crap without giving anything back to us.
But we wont help.you do it.

**Comment by Syprene** [comment]
> Any Mods you create for the Game from scratch belong to you (including pre-run Mods and in-memory Mods) and you can do whatever you want with them, as long as you don't sell them for money / try to make money from them and so long as you don’t distribute Modded Versions of the Game. Remember that a Mod means something that is your original work and that does not contain a substantial part of our code or content. You only own what you created; you do not own our code or content.

Straight from the Minecraft EULA, you're basically admitting to breaking the Minecraft EULA. Forge is so big that I'm sure this post won't matter, unless lets say all this comes to light, and everyone starts realizing that Minecraft is enforcing their EULA biased & unfairly.
