### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Pieter12345** [MinecraftForge/Installer#51]
Looking the the repository in its current state, it is not clear how to use this software without reading code. Having a brief guide on how to use this installer would make it a lot easier to use. This should be written or referred to in the `README.md` file.

**Comment by DaemonUmbra** [comment]
You do know the installer does basically nothing on its own and you would need to know code or scripting to use it properly, right?

**Comment by Pieter12345** [comment]
Yes, the installer actually crashes when running it without valid `install_profile.json` file. What I mean is that it would be very helpful to know what the installer can do and how to accomplish this (e.g. that one has to create an `install_profile.json` file and which options in there can be set to do what). This is all obtainable through investing time and reading sourcecode, but that is simply not user-friendly, hence the issue.

**Comment by DaemonUmbra** [comment]
Feel free to write the docs yourself...
