### ISSUE TITLE
Descriptive profile name

### ISSUE THREAD

**Issue by EzerArch** [MinecraftForge/Installer#54]
Forge itself and mod files somewhat follow a naming conversion.

For instance, I'd like to install Forge for 1.12.2, then the installer will create a "Forge 1.12.2-2847" (to sort by vanilla x modded) or "1.12.2 Forge 2847" (to sort by Minecraft version), instead of just "forge".

**Comment by LexManos** [comment]
The profile name is already configurable in the config json.
The default profile is there for convenience, not to spam the profile list.
