### ISSUE TITLE
Commandline switch for producing a client jar

### ISSUE THREAD

**Issue by ghost** [MinecraftForge/Installer#56]
Hi, I currently maintain a launcher that has Forge support. It currently works up to 1.12.x by running --installServer and --extract, adding those jars to classpath, and then changing the main class and adding on any arguments from the json file inside of the installer jar. 

What would be nice is to be able to have a --installClient for 1.13.x and up or similar, or some insight into how I could automate the installer for my launcher. I know about the new way things are done with regard to patching and obfuscation and that there seems to be some sort of build system in place. My current problem with the installer is that there's no way without interaction to produce a patched client jar for use with the game. 

Unlike MultiMC, I'm fine running the installer or doing things in a hacky way in the pursuit of having things work. So I'm open to any option I can get to get this working.

**Comment by FinnT730** [comment]
We don't support custom launchers.
We only support the Mojangs (AKA the vanilla) launcher.

**Comment by DaemonUmbra** [comment]
https://github.com/MinecraftForge/Installer/pull/31#issuecomment-242844174

**Comment by ghost** [comment]
@FinnT730 yes I'm aware but if you look here, cpw says https://github.com/MultiMC/MultiMC5/issues/2544#issuecomment-509668187
There is obviously some willingness to help other launchers.
@DaemonUmbra That's from 2016.. things have changed that you're obviously not aware of apparently.

**Comment by LexManos** [comment]
Mojang doesn't want 3rd party launches, and we're not going to help people make them. 

Make a mod manager like Twitch, don't make a launcher.

**Comment by FinnT730** [comment]
No, there is not.
The reason cpw wanted to help out is, MultiMc is made by one of the mojang people.

Custom launchers are a thing forge does not want not condone. Since any launcher that does bypass the mojangs launcher, can steal user login data

**Comment by Forkk** [comment]
> Mojang doesn't want 3rd party launches, and we're not going to help people make them.

This is still false, but you already knew that, didn't you?

@asineth have a look at this project here. This is how MultiMC is dealing with the Forge issue now https://github.com/ZekerZhayard/ForgeWrapper
