### ISSUE TITLE
White pixel in centre of screen while the Installer GUI is open

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/Installer#62]
![Screenshot demonstrating the issue](https://user-images.githubusercontent.com/3158390/116780894-33b0ff80-aa77-11eb-8b3a-064a7ca7e049.png)

**Comment by TheCurle** [comment]
That's caused by a second, zero-size panel, if i recall. Hiding it completely is next to impossible.
Check the iconization of the window, it should show two separate windows open, and one is unfocusable

**Comment by PaintNinja** [comment]
PR incoming that fixes it ;)
