### ISSUE TITLE
Add "Make offline installer jar" option

### ISSUE THREAD

**Issue by PaintNinja** [MinecraftForge/Installer#74]
With the forgedev build system now having the option of creating an offline installer with all deps included, I thought it might be a good idea to also have this option available to users as well as third-parties that want to redistribute the installer jar.

The option in the installer would essentially download all required deps and create a new installer jar based on itself with these deps included.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/Installer/commit/e3330721e60a962ae5c6d57b5fe99075dcc5d82a
